export const LangSkeleton_Bone = {
	en: {
		title: 'Brand Management',
		brand: {
			brand: 'Brand',
			keyword: 'Keyword',
			cuisine: 'Cuisine',
			status: 'Status',
			brandCode: 'Brand Code',
			brandName: 'Brand Name',
			lastEditTime: 'Last Edit',
			edit: 'Edit',
		},
		branch: {
			branch: 'Branch',
			keyword: 'Keyword',
			itemKeyword: 'Item Keyword',
			cuisine: 'Cuisine',
			status: 'Status',
			productCode: 'Product Code',
			productName: 'Product Name',
			stockNum: 'Stock Number',
			edit: 'Edit',
		},
		category: {
			category: 'Category',
			productName: 'Product Name',
			status: 'Status',
			edit: 'Edit',
		},
		area: {
			area: 'Area',
			keyword: 'Keyword',
			areaID: 'Area ID',
			areaName: 'Area Name',
			areaCode: 'Area Code',
			centering: 'Centering',
			edit: 'Edit',
		},
	},
	zh: {
		title: '品牌管理',
		brand: {
			brand: '品牌管理',
			keyword: '關鍵字',
			cuisine: '菜式',
			status: '狀態',
			brandCode: '品牌編號',
			brandName: '品牌名稱',
			lastEditTime: '上次修改日期',
			edit: '編輯',
		},
		branch: {
			branch: '商品管理',
			keyword: '區域關鍵字',
			itemKeyword: '名稱',
			cuisine: '菜式',
			status: '狀態',
			productCode: '商品編號',
			productName: '商品名稱',
			stockNum: '存貨編號',
			edit: '編輯',
		},
		category: {
			category: '商品分類',
			productName: '商品名稱',
			status: '狀態',
			edit: '編輯',
		},
		area: {
			area: '地區分類',
			keyword: '區域',
			areaID: '區域 ID',
			areaName: '地區名稱',
			areaCode: '區域碼',
			centering: '中心地標',
			edit: '編輯',
		},
	},
};

export const LangSkeleton_Application = {
	en: {
		title: 'Application',
		tandc: {
			tandc: 'T&C',
			contentTitle: 'Content Title',
			privacyPolicy: 'Privacy Policy',
			editBy: 'Edit By',
			editFrom: 'Edit From',
		},
		faqCategory: {
			faqCategory: 'FAQ Category',
			faqType: 'FAQ Type',
			faqStatus: 'Status(On/Off)',
			Updated: 'Updated',
			edit: 'Edit',
		},
		faq: {
			faq: 'FAQ',
			keyword: 'Keyword',
			faqCategory: 'FAQ Category',
			faqType: 'FAQ Type',
			question: 'Question',
			answer: 'Answer',
			faqStatus: 'Status(On/Off)',
			updated: 'Updated',
			edit: 'Edit',
		},
		contact: {
			contact: 'Contact',
			contactUs: 'Contact Us',
			contactTitle: 'Contact Title',
			contactContent: 'Contact Content',
			status: 'Status(On/Off)',
			edit: 'Edit',
		},
		tutorial: {
			tutorial: 'Tutorial',
		},
		appVersion: {
			appVersion: 'App Version',
			upgradeIOSVersion: 'iOS Version',
			upgradeAndroidVersion: 'Android Version',
			startingTime: 'Start On',
			endingTime: 'Ended On',
			status: 'Status(On/Off)',
			edit: 'Edit',
		},
		maintenance: {
			maintenance: 'Maintenance',
			systemMaintenance: 'System Maintenance',
			maintenanceContent: 'Maintenance Content',
			startDate: 'Start On',
			endedDate: 'Ended On',
		},
		clearCache: {
			clearCache: 'Clear Cache',
		},
	},
	zh: {
		title: '應用程式內容',
		tandc: {
			tandc: '一般 T&C',
			contentTitle: '條款及細則標題',
			privacyPolicy: '隱私政策標題',
			editBy: '更新由',
			editFrom: '更新於',
		},
		faqCategory: {
			faqCategory: '常見問題種類',
			faqType: '問題種類',
			faqStatus: '狀態(啟用/停用)',
			Updated: '更新於',
			edit: '編輯',
		},
		faq: {
			faq: '常見問題',
			faqCategory: '常見問題種類',
			keyword: '關鍵字',
			faqType: '問題種類',
			question: '問題',
			answer: '答案',
			faqStatus: '狀態(啟用/停用)',
			updated: '更新於',
			edit: '編輯',
		},
		contact: {
			contact: '聯絡我們',
			contactUs: '聯絡我們',
			contactTitle: '電郵主題',
			status: '狀態(啟用/停用)',
			edit: '編輯',
		},
		tutorial: {
			tutorial: '導覽圖片',
		},
		appVersion: {
			appVersion: '強制更新',
			upgradeIOSVersion: 'iOS 版本',
			upgradeAndroidVersion: 'Android 版本',
			startingTime: '開始時間',
			endingTime: '結束時間',
			status: '狀態(啟用/停用)',
			edit: '編輯',
		},
		maintenance: {
			maintenance: '系統維護',
			systemMaintenance: '系統維護',
			maintenanceContent: '維護頁面內容',
			startDate: '開始日期',
			endedDate: '結束日期',
		},
		clearCache: {
			clearCache: '清除快取',
		},
	},
};

export const LangSkeleton_promotion = {
	en: {
		title: 'Promotion',
		promotion: {
			banner: 'Banner',
			bannerSubject: 'Subject',
			promoID: 'Promo ID',
			bannerImg: 'Banner Image',
			startedDate: 'Started On',
			endedDate: 'Ended On',
			status: 'Status(On/Off)',
		},
		stampCard: {
			stampCard: 'Stamp Card',
			stampColor: 'Stamp Color',
			stampImg: 'Stamp Image',
			startedDate: 'Started On',
			endedDate: 'Ended On',
			status: 'Status(On/Off)',
		},
		referral: {
			referral: 'Referral',
			status: 'Status',
			name: 'Name',
			template: 'Template',
			referralStatus: 'Status(On/Off)',
		},
		promotional: {
			promotional: 'Promotional',
			campaignID: 'Campaign ID',
			internalSubject: 'Internal Subject',
			subject: 'Subject',
			status: 'Status(On/Off)',
			startedDate: 'Started On',
			endedDate: 'Ended On',
		},
		popCommercial: {
			popCommercial: 'Pop Commercial',
			title: 'Title',
			promoImage: 'Promote Image',
			status: 'Status(On/Off)',
			startedDate: 'Started On',
			endedDate: 'Ended On',
			mainImage: 'Main Image',
		},
	},
	zh: {
		title: '推廣管理',
		promotion: {
			banner: '首頁橫額',
			bannerSubject: '標題',
			promoID: '推廣 ID',
			bannerImg: '橫額圖片',
			startedDate: '開始日期',
			endedDate: '結束日期',
			status: '狀態 (啟用/停用)',
		},
		stampCard: {
			stampCard: '印仔卡圖案',
			stampColor: '印仔顏色',
			stampImg: '禮物圖案',
			startedDate: '開始日期',
			endedDate: '結束日期',
			status: '狀態 (啟用/停用)',
		},
		referral: {
			referral: '邀請好有',
			status: '狀態',
			name: '名稱',
			template: '模版',
			referralStatus: '狀態 (啟用/停用)',
		},
		promotional: {
			promotional: '宣傳頁面',
			campaignID: '活動 ID',
			internalSubject: '內部標題',
			subject: '標題',
			status: '狀態(啟用/停用)',
			startedDate: '開始日期',
			endedDate: '停止日期',
		},
		popCommercial: {
			popCommercial: '彈出式廣告',
			title: '名稱',
			promoImage: '宣傳圖片',
			status: '狀態 (啟用/停用)',
			startedDate: '開始日期',
			endedDate: '結束日期',
			mainImage: '主要圖片',
		},
	},
};
