import {
	AreaFakeData,
	BranchFakeData,
	BrandFakeData,
	CategoryFakeData,
} from './app/globalStyle';

export const brandFakeData: Array<BrandFakeData> = [
	{
		id: 1,
		brandCode: 7555545,
		brandName: 'test0218',
		brandStatus: true,
		modifiedDate: '2021',
	},
	{
		id: 2,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 3,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 4,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 5,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 6,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 7,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 8,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 9,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 10,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 11,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 12,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 13,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 14,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 15,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 16,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 17,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 18,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 19,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 20,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 21,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 22,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 23,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 24,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 25,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 26,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 27,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 28,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 29,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
	{
		id: 30,
		brandCode: 1234567,
		brandName: 'QA_Test排序',
		brandStatus: false,
		modifiedDate: '2021',
	},
];

export const branchFakeData: Array<BranchFakeData> = [
	{
		id: 1,
		branchName: 'QA我想吃東西',
		branchCode: 123456789,
		branchBrand: '翠園',
		branchStatus: true,
	},
	{
		id: 2,
		branchName: 'QA測試分店10',
		branchCode: 10,
		branchBrand: 'QA品牌名稱',
		branchStatus: true,
	},
];

export const categoryFakeData: Array<CategoryFakeData> = [
	{
		id: 1,
		categoryName: '節日產品',
		categoryStatus: true,
	},
	{
		id: 2,
		categoryName: '快餐',
		categoryStatus: true,
	},
];

export const areaFakeData: Array<AreaFakeData> = [
	{
		id: 1,
		areaId: 73,
		areaName: 'ABC',
		areaCode: '香港',
		areaCentering: 'ABC',
	},
	{
		id: 2,
		areaId: 46,
		areaName: '上環',
		areaCode: '香港',
		areaCentering: '無限極廣場',
	},
];
